### ISSUE TITLE
Copy to clipboard?

### ISSUE THREAD

**Issue by fleeting** [jjNford/github-repositories#10]
I wouldn't mind having a `copy to clipboard` icon like GitHub does on repo pages (https://github.com/jamesfleeting/paperkilledrock.com). This would come in handy for copying clone urls on those reusable projects (like my Drought html/css framework which I use to start new sites). Opening the extension and clicking copy would be nice. Of course this normally requires flash (as github does).

**Comment by jjNford** [comment]
links added for getting urls needed
