### ISSUE TITLE
Multiple Org switching

### ISSUE THREAD

**Issue by softwaregravy** [jjNford/github-repositories#14]
Cool extension, but I can't change to my org.

I have access to my own repositories, and 2 orgs (3 options in the drop down, total:  my account, org I own, org I've been added to).    I am unable to switch to the org's repositories that I own -- instead it just refreshes my own account's repositories.  I am able to switch to the third org, which I do not own, and back to my own account.

**Comment by jjNford** [comment]
hmm.. I am unable to reproduce this problem.  I am a member of a private organization and own an organization and am able to view all the repositories in each org.  Does pressing the manual refresh button fix this?  Does turning off the cache fix it?  Do you have a filter on?

I too have 3 options (my account, org I own, org I've been added to) and all are showing up correctly.

**Comment by softwaregravy** [comment]
The symptom is that the org won't select on the left -- when I select the org, it just reloads my personal account -- personal account is selected.  It 'feels' like 2 of the links in the org select menu are pointing to my personal account.

Pressing the refresh doesn't change anything.

Is there any way to "inspect source" on an extension so that I might help diagnose?

Do extensions interact?  Is it possible adblock or some other extension could be interfering?

**Comment by jjNford** [comment]
Can I get the account name and org name.  I think I have an idea of what may be happening.  Just got to a computer, going to take a quick look.  You can just pm me if you don't want to put ur account and org name in here.

**Comment by fleeting** [comment]
@softwaregravy I wouldn't think another extension is interfering however you can inspect the source of any extension by right clicking on the icon and clicking 'Inspect Popup'. That will open developer tools for the extension popup and let you see the url that the org is set to or any js errors you might be getting.

**Comment by jjNford** [comment]
@softwaregravy @jamesfleeting the source will be very hard to read as its all minified.  your best bet is to dl the master zip of this repo and load it as an unpacked extension.  then you can use the dev tools and put in some console output.  i'm about to push out an update though that will hopefully solve your problem.  all the context handling will be using ID's now rather than login names.  Let me know if it works for ya!

the dev branch also contains new development so if you find an error feel free to contribute (or if you have some cool ideas).

please rate in the chrome web store!

**Comment by jjNford** [comment]
@softwaregravy any luck today or are you still having this issue ?

**Comment by softwaregravy** [comment]
sorry for going MIA on this.  we had a release today and I've been distracted.

Will PM

**Comment by softwaregravy** [comment]
Yeah, it's working for me now.  Awesome.

**Comment by jjNford** [comment]
Awesome, glad to here!  Just got out of school, this is my first real
project (outside of work).  Any good review or word of mouth would help me
so much.  I live in the midwest and there is not a very big culture for
this kinda stuff.  Trying to fight my way west by pushing out personal
projects.

Again thanks for your feedback and help.

---

_JJ Ford_

facebook http://www.facebook.com/jj.n.ford |
twitterhttp://www.twitter.com/#!/jjNford|
linkedIn http://www.linkedin.com/in/jjnford

On Sun, Jan 29, 2012 at 11:55 AM, John Hinnegan <
reply@reply.github.com

**Comment by softwaregravy** [comment]
What school?

What major?

John Hinnegan
206-403-7982

On Sun, Jan 29, 2012 at 10:01 AM, JJ Ford <
reply@reply.github.com

**Comment by jjNford** [comment]
Midwestern State University (Wichita Falls, TX). Majored in both Computer Science and Mathematics.
