### ISSUE TITLE
Show notifications count

### ISSUE THREAD

**Issue by eduardocereto** [jjNford/github-repositories#19]
Hey I love this extension, and thought that it would be nice to add a feature request.
I'd like to know how many new notifications I have.

Probably a notification icon before the settings icon to match gitHub buttons.

Extra points if these are shown on the icon on toolbar as well.

**Comment by jjNford** [comment]
Thanks, I'm currently working on a rewrite to speed up caching for 3g data connections (hoping to be done in the next day or 2).  There are also some  CSS fixes I've made and problems I have discovered with the GitHub API and fixed them on my side.  I was also planning on looking into that as a feature... I'll keep you updated. 

Thanks again, spread the word!

**Comment by jjNford** [comment]
Notifications complete.  They will show up on the chrome badge as well as on the extensions notifications link just like GitHub.  Will post version 2.1 to the chrome store at some point tomorrow.
