### ISSUE TITLE
Turn Organizations dropmenu into an accordian

### ISSUE THREAD

**Issue by ProLoser** [jjNford/github-repositories#33]
There is a lot of available vertical space, and you already have the content pane scrolling on overflow. Take a look at Github's administration section, you'll see that you simply expand the Org or User you want to modify and the relevant subsections appear. Although it's not as necessary to 'expand' organizations since they all have only 1 section (I think).

Anyway, this would allow for fewer clickers and better usage of the available space.

**Comment by jjNford** [comment]
I like the idea of this Dean, sorry about the trouble with width dependencies.  I have made the width of the popup about 30px width with the merge of you pull request.  I added a width to the dashboard as a placeholder for the admin accordion navigation (trying to use same widths as GitHub - most people have liked the consistency).  I really appreciate your interest and would love if you could contribute to this feature.  The updates from the pull request are complete if you want to merge them with your fork.  Thx.

**Comment by jjNford** [comment]
If this were implemented I would also like to see as an option in the settings menu.  Users could choose between the 2 navigation styles (current and accordian).
