### ISSUE TITLE
Add ability to view / delete notifications

### ISSUE THREAD

**Issue by ProLoser** [jjNford/github-repositories#36]
I hate having to load github.com just to check / delete all my notifications

**Comment by ProLoser** [comment]
I'm tired and it's late, but you can checkout my 'notifications' fork and you'll see a basic implementation I stubbed out. Far from complete but a potential way to implement it.

I didn't feel like going through and adding the rest of the CSS at the moment lol.

**Comment by jjNford** [comment]
Its cool, I'll check it out when I get a free minute, just got back from 2 weeks out of town for work :S - one problem I foresee however is there is no RESTful API for notification.  It is possible to get the notifications by parsing the url body but I'm not sure if deleting from the extension would be possible.  I will have to look into it.
