### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by texastoland** [jjNford/github-repositories#39]
I wondered whether you're [informed](http://developer.apple.com/library/safari/#documentation/UserExperience/Conceptual/SafariExtensionsConversionGuide/Chapters/Chrome.html) how much effort would be required for Safari support? I'll pitch in if you think it's achievable.

**Comment by jjNford** [comment]
This is totally achievable.  The Chrome API's would have to be ported to Safari but there shouldn't be a problem.  The actually extension is out of date.  I started working on a rewrite (private repo right now) to update to GitHub's new styles and API as well as add some features and fix some problems the new Chrome APIs are causing.

If I had to guess the hardest part would be porting the OAuth 2 portion. Here is what I'm using for that (its a hack using the robots.txt page) https://github.com/jjNford/oauth2-chrome-extension

**Comment by Catincan** [comment]
Hi, lets put that on Catincan, I am ready to put some money for that.
