### ISSUE TITLE
Change default per_page in api call.

### ISSUE THREAD

**Issue by fleeting** [jjNford/github-repositories#7]
By default GitHub api returns only 30 results, this can be set to a max of 100 and then will either need to do paging in the extension (I could see paging below the list that would then call the next page of results or could loop through each page until all the results are returned and display all. I might be worried about the latter if somebody has watched a ton of repos, load time and the amount of items in the list could be much. I have 75 items in my watched and I don't think that is very much.

**Comment by jjNford** [comment]
This can easily be fixed be adding the parameter to the api_uri method parameter the the getAsyn is called. Will fix this soon.

**Comment by fleeting** [comment]
Yeah, per_page can be easily added. My suggestion might be to do paging. Not sure what per page limit you should do, my only worry would be somebody who just watches everything ending up with several hundred watches and the load time or crashing of the extension attempting to have javascript fetch all those items and then insert them into the html.

**Comment by jjNford** [comment]
All data is loaded and cached now.  A preference page will be developed so users can change cache settings.  A refresh button is also provided so users and manually refresh data.
